services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${ADMIN_USER}
      MYSQL_PASSWORD: ${ADMIN_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build:
      context: ./backend
    container_name: gym_backend
    restart: always
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - mysql


volumes:
  mysql_data:
