[project]
name = "gym-management-system"
version = "0.1.0"
description = "Gym Management System"
readme = "../README.md"
requires-python = ">=3.13"
dependencies = [
    "flask",
    "python-dotenv",
    "Flask-Login",
    "mysql-connector-python"
]
